### PR TITLE
fix: prevent DevToolsServer port conflicts on BrowserPool relaunch

### LINKED ISSUE #208: Double initialization of `DevToolsServer` leads to error in `web-scraper`
The `preLaunchHook` in Web Scraper initializes DevToolsServer:

https://github.com/apify/apify-sdk-js/blob/48e4c51241b45ca1e526e0ad45edef2127616650/packages/actor-scraper/web-scraper/src/internals/crawler_setup.ts#L318-L326

In case the page / browser crash (see highlighted section in the screenshot below), the dev tools server doesn't exit correctly and all subsequent initialization attempts will fail with port error.

Image

### PR DESCRIPTION
**Pull request by nikitachapovskii-dev**
Fixes a Web Scraper dev-mode issue where DevToolsServer was started from BrowserPool’s preLaunchHook on every browser launch/relaunch, causing EADDRINUSE port conflicts after browser/page crashes or pool relaunches. The PR makes DevToolsServer startup idempotent by starting it only once per actor process (reusing a cached start promise on subsequent hook calls) and registers a single Actor.on('exit') cleanup to stop the server.

Closes #208

### CODE REVIEW

File: packages/actor-scraper/web-scraper/src/internals/crawler_setup.ts [hunk 1]
```diff
@@ -225,6 +225,42 @@ export class CrawlerSetup implements CrawlerSetupOptions {
         this.initPromise = this._initializeAsync();
     }
 
+    // DevToolsServer must be started only once per actor process
+    private static _devToolsStartPromise: Promise<void> | null = null;
+    private static _devToolsServer: any | null = null;
+    private static _devToolsExitHookRegistered = false;
+
+    private static async _startDevToolsServerOnce(): Promise<void> {
```
Comment (barjin) [inline packages/actor-scraper/web-scraper/src/internals/crawler_setup.ts]:
```suggestion
    private static async startDevToolsServerOnce(): Promise<void> {
```

`private` is enough, eslint is right :)
